sudo: false
language: rust

# Run builds for all the trains (and more)
rust:
  - nightly
  - beta
  - stable
  # Minimum usable version of rust required.
  - 1.8.0

# Load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

os:
  - linux

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo --only nightly test -- --features nightly &&
      travis-cargo bench &&
      travis-cargo --only stable doc

notifications:
  email:
    on_success: never


env:
  global:
    # Override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
